### ISSUE TITLE
rewrite relative imports

### ISSUE THREAD

**Issue by i-Zaak** [dagush/fMRI_Observables#2]
https://github.com/dagush/fMRI_Observables/blob/371b44c782295a476188c4e320041e3251379df6/fMRI_Obs/FC.py#L11

You can write this as

```python
from . import BOLDFilters
```

**Comment by dagush** [comment]
Sorry about this, I forgot to answer. Yes, this is more or less what we ended doing... ;-)
Thanks!

**Comment by i-Zaak** [comment]
You are welcome :)
